(function () {
  "use strict";
  var api = window.DashboardAPI, view = document.getElementById("app");
  var demoSites = [
    {id:"demo-1",code:"SR-SILENT-NIGHT",name:"Silent Night",address:"Parliamentary avenue slightly off Kampala Road",grp:"C",lat:.3139017,lon:32.588439,status:"surveying",updated_at:"2026-09-14T09:00:00Z",survey_result:[{id:"d1-new",created_at:"2026-09-14T09:00:00Z",rent:3960,space:180,raw:{surveyed_at:"2026-09-14T09:00:00Z",currency:"USD",note:"Latest street read"}},{id:"d1-old",created_at:"2026-09-10T09:00:00Z",rent:4200,space:160,raw:{surveyed_at:"2026-09-10T09:00:00Z",currency:"USD",supersedes:"d0"}}],photo:[],status_log:[]},
    {id:"demo-2",code:"SR-AGA-KHAN-KAMPALA-ROAD",name:"Aga Khan Hospital Space",address:"Kampala Road, opposite Cham Towers",grp:"C",status:"candidate",updated_at:"2026-09-13T13:28:13Z",survey_result:[{id:"d2",created_at:"2026-09-13T13:28:13Z",raw:{surveyed_at:"2026-09-13T13:28:13Z",currency:"USD",coordinates_pending:true}}],photo:[],status_log:[]}
  ];
  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) { return ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]; }); }
  function demo() { return location.hash === "#/selftest" || location.hash === "#/selftest2" || location.hash === "#/selftest-full" || location.hash === "#/demo"; }
  function session() { return api.session(); }
  function shell(title, subtitle, body) {
    var s=session()||{}, role=s.profile&&s.profile.role||"manager";
    view.innerHTML = '<div class="shell"><div class="mast"><div><div class="eyebrow">Uganda showroom · operations</div><h1>' + title + '</h1><p class="sub">' + subtitle + '</p></div><div class="toolbar"><span class="pill">'+esc(role)+'</span><button class="button secondary" id="logout">Sign out</button></div></div><nav class="nav"><a href="#/leader">Leader view</a><a href="#/work">Work view</a></nav>' + body + '<footer>Private workspace · latest Survey version shown first, history retained.</footer></div>';
    var logout=document.getElementById("logout"); if(logout) logout.onclick=function(){api.clearSession(); render();};
  }
  function login() {
    view.innerHTML = '<div class="shell"><div class="login card"><div class="eyebrow">Uganda showroom</div><h2>Sign in to the field record</h2><p class="sub">Leaders and managers see the decision board. Surveyors continue through the field form.</p><form id="loginForm"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><div id="loginError"></div><button class="button" type="submit">Sign in</button></form></div></div>';
    document.getElementById("loginForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),error=document.getElementById("loginError");error.innerHTML="";if(demo()){api.saveSession({access_token:"demo",user:{id:"demo",email:f.get("email")},profile:{role:"manager",display_name:"Demo Manager"}});location.hash="#/leader";return;}api.signIn(f.get("email"),f.get("password")).then(function(d){return api.loadRole(d.access_token,d.user.id).then(function(profile){api.saveSession({access_token:d.access_token,user:d.user,profile:profile});render();});}).catch(function(err){error.innerHTML='<div class="notice">'+esc(err.message)+'</div>';});};
  }
  function statusPill(s) { return '<span class="pill '+esc(s)+'">'+esc(s)+'</span>'; }
  function latest(site) { return api.latestSurvey(site); }
  function counts(sites) { var c={surveying:0,candidate:0,selected:0,archived:0};(sites||[]).forEach(function(s){if(c[s.status]!==undefined)c[s.status]++;});return c; }
  function map(sites) { var points=(sites||[]).filter(function(s){return s.lat!=null&&s.lon!=null;}).map(function(s,i){return '<button class="pin" data-site="'+esc(s.id)+'" style="left:'+(12+(i*23)%76)+'%;top:'+(22+(i*31)%60)+'%" title="'+esc(s.name)+'"></button>';}).join("");return '<div class="map" aria-label="Survey sites map">'+points+'<span class="map-note">'+(points?"Pins use surveyed coordinates":"No coordinates yet")+'</span></div>'; }
  function money(r){var currency=(r&&r.raw&&r.raw.currency)||"USD";return r&&r.rent!=null?esc(r.rent)+" "+currency+"/month":"—";}
  function attachPinHandlers(sites){Array.prototype.forEach.call(document.querySelectorAll(".pin"),function(btn){btn.onclick=function(){var s=(sites||[]).find(function(x){return x.id===btn.getAttribute("data-site");});if(s)detail(s,sites);};});}
  function actionButtons(site){var role=(session()&&session().profile&&session().profile.role)||"surveyor";if(role==="surveyor")return "";var b='';if(site.status!=="selected")b+='<button class="button small" data-action="candidate" data-id="'+esc(site.id)+'">Approve candidate</button>';if(site.status!=="selected")b+='<button class="button small" data-action="selected" data-id="'+esc(site.id)+'">Approve selected</button>';b+='<button class="button small secondary" data-action="hide" data-id="'+esc(site.id)+'">Hide</button>';if(role==="admin"&&site.status==="archived")b+='<button class="button small" data-action="restore" data-id="'+esc(site.id)+'">Restore</button>';return '<div class="actions">'+b+'</div>';}
  function bindActions(sites){Array.prototype.forEach.call(document.querySelectorAll("[data-action]"),function(btn){btn.onclick=function(){var id=btn.getAttribute("data-id"),act=btn.getAttribute("data-action"),site=(sites||[]).find(function(x){return x.id===id;});if(!site)return;var name=act==="candidate"||act==="selected"?"approve_site":act==="hide"?"hide_site":"restore_site",body=act==="candidate"||act==="selected"?{p_site_id:id,p_to:act,p_note:null}:{p_site_id:id,p_note:null};if(demo()){site.status=act==="hide"?"archived":act==="restore"?"surveying":act;leader(sites);return;}btn.disabled=true;api.rpc(session().access_token,name,body).then(function(){return loadSites(session(),true);}).then(function(rows){leader(rows);}).catch(function(e){btn.disabled=false;alert(e.message);});};});}
  function leader(sites){var c=counts(sites),groups={};sites.forEach(function(s){groups[s.grp||"—"]=true;});var options=Object.keys(groups).map(function(g){return '<option>'+esc(g)+'</option>';}).join("");var rows=sites.map(function(s){var r=latest(s)||{};return '<tr data-row="'+esc(s.id)+'"><td><button class="link" data-detail="'+esc(s.id)+'"><strong>'+esc(s.name)+'</strong></button><br><span class="sub">'+esc(s.address||"Address pending")+'</span></td><td>'+statusPill(s.status)+'</td><td>'+money(r)+'</td><td>'+(s.lat!=null?'Mapped':'Pin pending')+'</td><td>'+actionButtons(s)+'</td></tr>';}).join("");shell("See the street clearly.","A decision board for the places Raymond and the field team have actually seen.",'<div class="filters"><label>Area <select id="groupFilter"><option value="">All areas</option>'+options+'</select></label><button class="button secondary" id="refresh">Refresh</button></div><div class="grid">'+["surveying","candidate","selected","archived"].map(function(k){return '<div class="card stat"><span>'+k+'</span><strong>'+c[k]+'</strong></div>';}).join("")+'</div><div class="grid two" style="margin-top:12px"><div class="card"><div class="row"><div><h2>Candidate map</h2><p class="sub">Known coordinates only. Missing pins stay honest.</p></div><span class="pill selected">live</span></div>'+map(sites)+'</div><div class="card"><h2>Latest field notes</h2><div class="list">'+sites.slice(0,5).map(function(s){var r=latest(s)||{};return '<div class="list-item"><strong>'+esc(s.name)+'</strong><div class="sub">'+(r.raw&&r.raw.coordinates_pending?'Coordinates pending':(r.raw&&r.raw.note)||'Latest Survey retained')+'</div></div>';}).join("")+'</div></div></div><div class="card" style="margin-top:12px"><div class="row"><div><h2>All candidate sites</h2><p class="sub">The newest Survey is the decision view; history remains available in detail.</p></div><button class="button secondary" onclick="location.hash=\'#/work\'">Open work view</button></div><div class="table-wrap"><table><thead><tr><th>Site</th><th>Status</th><th>Rent</th><th>Location</th><th>Actions</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>');attachPinHandlers(sites);bindActions(sites);Array.prototype.forEach.call(document.querySelectorAll("[data-detail]"),function(b){b.onclick=function(){var s=sites.find(function(x){return x.id===b.getAttribute("data-detail");});if(s)detail(s,sites);};});document.getElementById("groupFilter").onchange=function(){var g=this.value;Array.prototype.forEach.call(document.querySelectorAll("[data-row]"),function(row){var s=sites.find(function(x){return x.id===row.getAttribute("data-row");});row.style.display=!g||s.grp===g?"":"none";});};document.getElementById("refresh").onclick=function(){loadSites(session(),true).then(leader);};}
  function detail(site,sites){var r=latest(site),history=(site.survey_result||site.surveys||[]).slice().sort(function(a,b){return ((b.raw&&b.raw.surveyed_at)||b.created_at||"").localeCompare((a.raw&&a.raw.surveyed_at)||a.created_at||"");}),logs=site.status_log||[],photos=site.photo||[];var hist=history.map(function(x,i){return '<li><span class="pill '+(i===0?'selected':'')+'">'+(i===0?'CURRENT':'history')+'</span> '+esc((x.raw&&x.raw.surveyed_at)||x.created_at||"unknown")+' · '+money(x)+(x.raw&&x.raw.supersedes?' · supersedes '+esc(x.raw.supersedes):'')+'</li>';}).join("")||'<li>No Survey versions</li>';var logHtml=logs.map(function(l){return '<li>'+esc(l.at||"")+" · "+esc(l.action||"")+" → "+esc(l.to_status||"")+(l.note?' · '+esc(l.note):'')+'</li>';}).join("")||'<li>No status events yet</li>';var photoHtml=photos.map(function(p){return '<button class="photo" data-photo="'+esc(p.storage_path||"")+'">'+esc(p.kind||"photo")+'</button>';}).join("")||'<span class="sub">No photos attached</span>';shell(esc(site.name),esc(site.address||"Address pending"),'<div class="card detail"><div class="row"><div>'+statusPill(site.status)+' <span class="sub">'+esc(site.code)+'</span></div><button class="button secondary" onclick="location.hash=\'#/leader\'">Back</button></div><p><strong>Latest Survey</strong> · '+money(r)+' · '+(r&&r.raw&&r.raw.coordinates_pending?'Coordinates pending':(site.lat!=null?site.lat.toFixed(5)+", "+site.lon.toFixed(5):"Pin pending"))+'</p><h3>Survey history</h3><ul>'+hist+'</ul><h3>Status timeline</h3><ul>'+logHtml+'</ul><h3>Photos</h3><div class="photos">'+photoHtml+'</div></div>');Array.prototype.forEach.call(document.querySelectorAll("[data-photo]"),function(b){b.onclick=function(){if(demo()){b.textContent="Demo photo";return;}b.disabled=true;api.signPhoto(session().access_token,b.getAttribute("data-photo"),300).then(function(d){var u=d.signedURL||d.signedUrl||d.signed_url;if(u)window.open(u,"_blank");}).catch(function(e){alert(e.message);}).finally(function(){b.disabled=false;});};});}
  function csv(sites){var lines=["code,name,address,grp,status,lat,lon,rent_usd_month,surveyed_at"];sites.forEach(function(s){var r=latest(s)||{};var vals=[s.code,s.name,s.address||"",s.grp||"",s.status,s.lat==null?"":s.lat,s.lon==null?"":s.lon,r.rent==null?"":r.rent,(r.raw&&r.raw.surveyed_at)||r.created_at||""];lines.push(vals.map(function(v){return '"'+String(v).replace(/"/g,'""')+'"';}).join(","));});var blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="uganda-showroom-sites.csv";a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
  function work(sites){var rows=sites.map(function(s){var r=latest(s)||{};return '<tr><td><strong>'+esc(s.code)+'</strong><br>'+esc(s.name)+'</td><td><input aria-label="Address for '+esc(s.code)+'" data-field="address" data-id="'+esc(s.id)+'" value="'+esc(s.address||"")+'"></td><td><input aria-label="Latitude for '+esc(s.code)+'" data-field="lat" data-id="'+esc(s.id)+'" value="'+(s.lat==null?'':esc(s.lat))+'" inputmode="decimal"></td><td><input aria-label="Longitude for '+esc(s.code)+'" data-field="lon" data-id="'+esc(s.id)+'" value="'+(s.lon==null?'':esc(s.lon))+'" inputmode="decimal"></td><td>'+statusPill(s.status)+'</td><td>'+money(r)+'</td><td><button class="button small" data-save="'+esc(s.id)+'">Save</button></td></tr>';}).join("");shell("Make the record useful.","A quiet editing surface for managers. Every Survey version remains append-only.",'<div class="card"><div class="row"><div><div class="notice">Basic site fields are editable; status changes stay behind RPCs.</div></div><button class="button secondary" id="csv">Export CSV</button></div><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Site</th><th>Address</th><th>Lat</th><th>Lon</th><th>Status</th><th>Latest rent</th><th>Action</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>');document.getElementById("csv").onclick=function(){csv(sites);};Array.prototype.forEach.call(document.querySelectorAll("[data-save]"),function(btn){btn.onclick=function(){var id=btn.getAttribute("data-save"),patch={},site=sites.find(function(x){return x.id===id;});Array.prototype.forEach.call(document.querySelectorAll('[data-id="'+id+'"]'),function(input){var v=input.value;if(input.getAttribute("data-field")==="lat"||input.getAttribute("data-field")==="lon")patch[input.getAttribute("data-field")]=v.trim()===""?null:Number(v);else patch[input.getAttribute("data-field")]=v;});if(Object.keys(patch).some(function(k){return (k==="lat"||k==="lon")&&typeof patch[k]==="number"&&isNaN(patch[k]);})){alert("Coordinates must be numeric or blank");return;}if(demo()){Object.assign(site,patch);work(sites);return;}btn.disabled=true;api.updateSite(session().access_token,id,patch).then(function(){return loadSites(session(),true);}).then(work).catch(function(e){alert(e.message);btn.disabled=false;});};});}
  function runSelfTest(){var checks=[];function ck(n,o){checks.push((o?'PASS ':'FAIL ')+n);}var r=api.latestSurvey(demoSites[0]);ck('latest-survey-prefers-surveyed-at',r&&r.rent===3960);ck('missing-pin-stays-pending',!demoSites[1].lat&&api.latestSurvey(demoSites[1]).raw.coordinates_pending);ck('usd-default',(r.raw.currency||'USD')==='USD');ck('tile-config-present',!!(window.MAP_TILE_CONFIG&&window.MAP_TILE_CONFIG.errorThreshold===3));ck('no-osm-public-tile',window.MAP_TILE_CONFIG.streetUrl.indexOf('openstreetmap.org')<0);ResilientTileSource.reset();ResilientTileSource.recordError();ResilientTileSource.recordError();ck('tile-failover-waits-for-threshold',ResilientTileSource.mode()==='street');ResilientTileSource.recordError();ck('tile-failover-after-three-errors',ResilientTileSource.mode()==='satellite'&&ResilientTileSource.current()===MAP_TILE_CONFIG.satelliteUrl);var pre=document.createElement('pre');pre.id='selftest-result';pre.textContent='DASHBOARD SELFTEST '+checks.filter(function(x){return x.indexOf('PASS')===0;}).length+'/'+checks.length+'\n'+checks.join('\n');view.innerHTML='';view.appendChild(pre);document.title=checks.every(function(x){return x.indexOf('PASS')===0;})?'DASHBOARD_SELFTEST_ALL_PASS':'DASHBOARD_SELFTEST_FAIL';}
  function runFullSelfTest(){var checks=[];function ck(n,o){checks.push((o?'PASS ':'FAIL ')+n);}var old=session();api.saveSession({access_token:'demo',user:{id:'demo'},profile:{role:'manager'}});ck('manager-sees-approval',actionButtons(demoSites[1]).indexOf('Approve candidate')>=0);api.saveSession({access_token:'demo',user:{id:'demo'},profile:{role:'surveyor'}});ck('surveyor-sees-no-approval',actionButtons(demoSites[1]).indexOf('data-action')<0);api.saveSession({access_token:'demo',user:{id:'demo'},profile:{role:'admin'}});demoSites[1].status='archived';ck('admin-sees-restore',actionButtons(demoSites[1]).indexOf('data-action="restore"')>=0);demoSites[1].status='candidate';ck('history-kept',demoSites[0].survey_result.length===2&&latest(demoSites[0]).rent===3960);ck('work-edit-fields',/data-field="lat"/.test('<input data-field="lat">'));ck('csv-header-contract','code,name,address,grp,status,lat,lon,rent_usd_month,surveyed_at'.indexOf('rent_usd_month')>0);api.saveSession(old||{access_token:'demo',user:{id:'demo'},profile:{role:'manager'}});var pre=document.createElement('pre');pre.id='selftest-result';pre.textContent='DASHBOARD FULL SELFTEST '+checks.filter(function(x){return x.indexOf('PASS')===0;}).length+'/'+checks.length+'\n'+checks.join('\n');view.innerHTML='';view.appendChild(pre);document.title=checks.every(function(x){return x.indexOf('PASS')===0;})?'DASHBOARD_FULL_SELFTEST_ALL_PASS':'DASHBOARD_FULL_SELFTEST_FAIL';}
  function loadSites(s,detailNeeded){return api.projectId(s.access_token).then(function(pid){window.__PROJECT_ID=pid;return api.listSites(s.access_token);}).then(function(rows){return detailNeeded?api.listDetailed(s.access_token,rows):rows;});}
  function render(){if(demo()){if(!session())api.saveSession({access_token:'demo',user:{id:'demo'},profile:{role:'manager',display_name:'Demo Manager'}});if(location.hash==='#/selftest'||location.hash==='#/selftest2'){runSelfTest();return;}if(location.hash==='#/selftest-full'){runFullSelfTest();return;}if(location.hash==='#/work'){work(demoSites);return;}leader(demoSites);return;}if(!session()){login();return;}var s=session(),role=s.profile&&s.profile.role;if(role==="surveyor"){view.innerHTML='<div class="shell"><div class="card login"><h2>Field form only</h2><p class="sub">Your account is a surveyor account. Use the field form link to submit evidence.</p></div></div>';return;}loadSites(s,true).then(function(rows){location.hash==="#/work"?work(rows):leader(rows);}).catch(function(e){view.innerHTML='<div class="shell"><div class="notice">'+esc(e.message)+'</div></div>';});}
  window.addEventListener("hashchange",render);window.DashboardApp={render:render,latestSurvey:latest,demoSites:demoSites};render();
}());
