(function () {
  "use strict";
  var api = window.DashboardAPI, view = document.getElementById("app");
  var demoSites = [
    {id:"demo-1",code:"SR-SILENT-NIGHT",name:"Silent Night",address:"Parliamentary avenue slightly off Kampala Road",grp:"C",lat:.3139017,lon:32.588439,status:"surveying",survey_result:[{created_at:"2026-09-14T09:00:00Z",raw:{surveyed_at:"2026-09-14T09:00:00Z",currency:"USD"},rent:3960}]},
    {id:"demo-2",code:"SR-AGA-KHAN-KAMPALA-ROAD",name:"Aga Khan Hospital Space",address:"Kampala Road, opposite Cham Towers",grp:"C",status:"surveying",survey_result:[{created_at:"2026-09-14T13:28:13Z",raw:{surveyed_at:"2026-09-14T13:28:13Z",currency:"USD",coordinates_pending:true}}]}
  ];
  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) { return ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]; }); }
  function demo() { return location.hash === "#/selftest" || location.hash === "#/selftest2"; }
  function session() { return api.session(); }
  function shell(title, subtitle, body) { view.innerHTML = '<div class="shell"><div class="mast"><div><div class="eyebrow">Uganda showroom · operations</div><h1>' + title + '</h1><p class="sub">' + subtitle + '</p></div><div class="toolbar"><button class="button secondary" id="logout">Sign out</button></div></div>' + body + '<footer>Private workspace · latest Survey version shown first, history retained.</footer></div>'; var logout=document.getElementById("logout"); if(logout) logout.onclick=function(){api.clearSession(); render();}; }
  function login() { view.innerHTML = '<div class="shell"><div class="login card"><div class="eyebrow">Uganda showroom</div><h2>Sign in to the field record</h2><p class="sub">Leaders and managers see the decision board. Surveyors continue through the field form.</p><form id="loginForm"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><div id="loginError"></div><button class="button" type="submit">Sign in</button></form></div></div>'; document.getElementById("loginForm").onsubmit=function(e){e.preventDefault(); var f=new FormData(e.target); var error=document.getElementById("loginError"); error.innerHTML=""; if(demo()){api.saveSession({access_token:"demo",user:{id:"demo",email:f.get("email")},profile:{role:"manager",display_name:"Demo Manager"}}); render(); return;} api.signIn(f.get("email"),f.get("password")).then(function(d){return api.loadRole(d.access_token,d.user.id).then(function(profile){api.saveSession({access_token:d.access_token,user:d.user,profile:profile});render();});}).catch(function(err){error.innerHTML='<div class="notice">'+esc(err.message)+'</div>';});}; }
  function statusPill(s) { return '<span class="pill '+esc(s)+'">'+esc(s)+'</span>'; }
  function map(sites) { var points=sites.filter(function(s){return s.lat!=null&&s.lon!=null;}).map(function(s,i){return '<i class="pin" style="left:'+(18+(i*29)%70)+'%;top:'+(28+(i*37)%54)+'%" title="'+esc(s.name)+'"></i>';}).join(""); return '<div class="map" aria-label="Survey sites map">'+points+'</div>'; }
  function latest(site) { return api.latestSurvey(site); }
  function leader(sites) { var counts={surveying:0,candidate:0,selected:0,archived:0}; sites.forEach(function(s){counts[s.status]=(counts[s.status]||0)+1;}); var rows=sites.map(function(s){var r=latest(s)||{};var currency=(r.raw&&r.raw.currency)||"USD"; return '<tr><td><strong>'+esc(s.name)+'</strong><br><span class="sub">'+esc(s.address||"Address pending")+'</span></td><td>'+statusPill(s.status)+'</td><td>'+(r.rent!=null?esc(r.rent)+" "+currency+"/month":"—")+'</td><td>'+(s.lat!=null?'Mapped':'Pin pending')+'</td></tr>';}).join(""); shell("See the street clearly.","A decision board for the places Raymond and the field team have actually seen.",'<div class="grid">'+Object.keys(counts).slice(0,4).map(function(k){return '<div class="card stat"><span>'+k+'</span><strong>'+counts[k]+'</strong></div>';}).join("")+'</div><div class="grid two" style="margin-top:12px"><div class="card"><div class="row"><div><h2>Candidate map</h2><p class="sub">Known coordinates only. Missing pins stay honest.</p></div><span class="pill selected">live</span></div>'+map(sites)+'</div><div class="card"><h2>Latest field notes</h2><div class="list">'+sites.slice(0,5).map(function(s){var r=latest(s)||{};return '<div class="list-item"><strong>'+esc(s.name)+'</strong><div class="sub">'+(r.raw&&r.raw.coordinates_pending?'Coordinates pending':'Latest Survey retained')+'</div></div>';}).join("")+'</div></div></div><div class="card" style="margin-top:12px"><div class="row"><div><h2>All candidate sites</h2><p class="sub">The newest Survey is the decision view; history remains available in detail.</p></div><button class="button secondary" onclick="location.hash=\'#/work\'">Open work view</button></div><div class="table-wrap"><table><thead><tr><th>Site</th><th>Status</th><th>Rent</th><th>Location</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'); }
  function work(sites) { var rows=sites.map(function(s){var r=latest(s)||{};return '<tr><td><strong>'+esc(s.code)+'</strong><br>'+esc(s.name)+'</td><td><input aria-label="Address for '+esc(s.code)+'" value="'+esc(s.address||"")+'"></td><td>'+statusPill(s.status)+'</td><td>'+(r.raw&&r.raw.currency||"USD")+'</td><td><button class="button secondary" disabled>Save</button></td></tr>';}).join(""); shell("Make the record useful.","A quiet editing surface for managers. Every Survey version remains append-only.",'<div class="card"><div class="notice">Editing controls are scaffolded here; approval and restore actions arrive with the work-view milestone.</div><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Site</th><th>Address</th><th>Status</th><th>Currency</th><th>Action</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'); }
  function runSelfTest() { var checks=[]; function ck(name, ok){checks.push((ok?'PASS ':'FAIL ')+name);} var latest=api.latestSurvey(demoSites[0]); ck('latest-survey-prefers-surveyed-at', latest && latest.rent===3960); ck('missing-pin-stays-pending', !demoSites[1].lat && api.latestSurvey(demoSites[1]).raw.coordinates_pending); ck('usd-default', (latest.raw.currency||'USD')==='USD'); ck('tile-config-present', !!(window.MAP_TILE_CONFIG && window.MAP_TILE_CONFIG.errorThreshold===3)); ck('no-osm-public-tile', window.MAP_TILE_CONFIG.streetUrl.indexOf('openstreetmap.org')<0); ResilientTileSource.reset(); ResilientTileSource.recordError(); ResilientTileSource.recordError(); ck('tile-failover-waits-for-threshold', ResilientTileSource.mode()==='street'); ResilientTileSource.recordError(); ck('tile-failover-after-three-errors', ResilientTileSource.mode()==='satellite' && ResilientTileSource.current()===MAP_TILE_CONFIG.satelliteUrl); var pre=document.createElement('pre'); pre.id='selftest-result'; pre.textContent='DASHBOARD SELFTEST '+checks.filter(function(x){return x.indexOf('PASS')===0;}).length+'/'+checks.length+'\n'+checks.join('\n'); view.innerHTML=''; view.appendChild(pre); document.title=checks.every(function(x){return x.indexOf('PASS')===0;})?'DASHBOARD_SELFTEST_ALL_PASS':'DASHBOARD_SELFTEST_FAIL'; }
  function loadSites(s) { return api.projectId(s.access_token).then(function(pid){window.__PROJECT_ID=pid;return api.listSites(s.access_token);}); }
  function render() { if(demo()){if(!session()) api.saveSession({access_token:'demo',user:{id:'demo'},profile:{role:'manager',display_name:'Demo Manager'}}); if(location.hash==='#/selftest'||location.hash==='#/selftest2'){runSelfTest();return;}} if(!session()){login();return;} var s=session(), role=s.profile&&s.profile.role; if(role==="surveyor"){view.innerHTML='<div class="shell"><div class="card login"><h2>Field form only</h2><p class="sub">Your account is a surveyor account. Use the field form link to submit evidence.</p></div></div>';return;} if(demo()){leader(demoSites);return;} loadSites(s).then(leader).catch(function(e){view.innerHTML='<div class="shell"><div class="notice">'+esc(e.message)+'</div></div>';}); }
  window.addEventListener("hashchange", function(){ if(location.hash==="#/work"&&session()&&(session().profile.role!=="surveyor")){ if(demo()){work(demoSites);} else {loadSites(session()).then(work);} } else render(); });
  window.DashboardApp={render:render,latestSurvey:latest}; render();
}());
